Update to xxHash 0.8.0
HolyWu/L-SMASH-Works pull request #15
Opened 2021-01-24 06:27 UTC by Astrum-polaris

Use the new XXH3 that is stabilized in this version

2021-01-31 15:21 UTC, HolyWu requested changes

2021-01-31 15:21 UTC, HolyWu commented on common/lwindex.c
> +    if( fscanf( index, "<FileHash=0x%" PRIx64 ">\n", &file_hash ) != 1
It shoueld be `SCN` instead of `PRI`.

2021-02-03 12:57 UTC, Astrum-polaris commented on common/lwindex.c
> +    if( fscanf( index, "<FileHash=0x%" PRIx64 ">\n", &file_hash ) != 1
Done.
Thank you!

2021-02-03 14:34 UTC, HolyWu approved these changes

2021-02-03 14:36 UTC, merged