Set frame properties and variables for LSMASHVideoSource too
HolyWu/L-SMASH-Works pull request #18
Opened 2021-04-21 23:08 UTC by Asd-g

2021-04-22 05:29 UTC, HolyWu requested changes
Well, I was both busy and lazy before so I just blindly merged the previous PR and hence missed the chance to catch the flaws.

2021-04-22 05:29 UTC, HolyWu commented on AviSynth/libavsmash_source.cpp
> +    int den = av_frame->sample_aspect_ratio.den;
Using `sample_aspect_ratio` from `av_frame` is invalid since the exported variable is meant for the entire video and not for per frame. You should use `sample_aspect_ratio` from either the container or the codec, otherwise it's simply a duplicate of `_SARNum` and `_SARDen` in frame properties and then the exported variables become meaningless. The same thing applies to LWLibavVideoSource in the previous PR. See ffms2's code for how it's done.

2021-04-22 21:24 UTC, Asd-g commented on AviSynth/libavsmash_source.cpp
> +    int den = av_frame->sample_aspect_ratio.den;
Thanks for your time.

The reason to set those variables is accessing SAR outside runtime scope and using them for resize.
_SARNum /_SARDen values cannot be used for resizing because they should be accessed with ScripClip/FrameEvaluate and then resize within ScriptClip which is not possible because SciptClip input and output must have same dimensions. There is dirty way to use _SARNum /_SARDen values in such scenario - they have to be saved in temp file and they have to be retrieved from only one frame not every frame.

2021-04-23 02:30 UTC, HolyWu approved these changes

2021-04-23 02:31 UTC, merged